/* ===== GENERATED by build/regen-strava.py — DO NOT HAND-EDIT =====
   Latest Strava activity: type + duration + start, nothing else.
   Rewritten on a schedule by .github/workflows/strava.yml.
   ================================================================ */
var STRAVA = {"type": "Walk", "moving_s": 2698, "start": "2026-09-01T22:55:50Z"};
