/* ===== GENERATED by build/regen-strava.py — DO NOT HAND-EDIT =====
   Latest Strava activity: type + duration + start, nothing else.
   Rewritten on a schedule by .github/workflows/strava.yml.
   ================================================================ */
var STRAVA = {"type": "WeightTraining", "moving_s": 1296, "start": "2026-09-02T17:34:23Z"};
